version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/workorders
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=workorders
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssw0rd
