# Generated by Django 3.2.5 on 2023-07-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('room', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('cleaning', 'Cleaning'), ('maid_request', 'Maid Request'), ('technician_request', 'Technician Request'), ('amenity_request', 'Amenity Request')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancel')], max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workorders.workorder')),
                ('amenity_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaidRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workorders.workorder')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workorders.workorder')),
                ('defect_type', models.CharField(max_length=50)),
            ],
        ),
    ]
