# Generated by Django 3.2.6 on 2023-07-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='type',
            new_name='work_order_type',
        ),
    ]
