# Generated by Django 3.2.6 on 2023-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_rename_type_workorder_work_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('user', 'Guest'), ('maid', 'Maid')], max_length=20),
        ),
    ]
